cask_args appdir: "~/Applications"

tap "dart-lang/dart"
tap "felixkratz/formulae"
tap "fluxcd/tap"
tap "go-task/tap"
tap "hashicorp/tap"
tap "localstack/tap"
tap "nikitabobko/tap"
tap "terraform-docs/tap"
tap "sass/sass"

brew "awscli"
brew "awslogs"
brew "coreutils"
brew "dockutil"
brew "felixkratz/formulae/borders"
brew "fluxcd/tap/flux"
brew "fzf"
brew "go-task/tap/go-task"
brew "go"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "helm"
brew "hugo"
brew "jq"
brew "kubeconform"
brew "kubectl-cnpg"
brew "kubelogin"
brew "kubernetes-cli"
brew "kubeseal"
brew "localstack/tap/localstack-cli"
brew "mas"
brew "poetry"
brew "sass/sass/sass"
brew "shellcheck"
brew "smartmontools"
brew "terraform-docs"
brew "terraform-local"
brew "tflint"
brew "tz"
brew "uv"
brew "yazi"
brew "pre-commit"

cask "aerospace"
cask "appcleaner"
cask "balenaetcher"
cask "clop"
cask "coconutbattery"
cask "daisydisk"
cask "ghostty"
cask "itsycal"
cask "knockknock"
cask "lens"
cask "logi-options+"
cask "logseq"
cask "lunar"
cask "orbstack"
cask "qmk-toolbox"
cask "rectangle"
cask "vial"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "wireshark-app"
cask "setchy/brews/atlassify"

cask "font-input"
cask "font-inter"
cask "font-iosevka"
cask "font-jetbrains-mono"

# mas "AmorphousDiskMark", id: 1168254295
# mas "Amphetamine", id: 937984704
# mas "Bitwarden", id: 1352778147
# mas "Discovery", id: 1381004916
# mas "Hand Mirror", id: 1502839586
# mas "Hidden Bar", id: 1452453066
# mas "Home Assistant", id: 1099568401
# mas "Hush", id: 1544743900
# mas "Ivory", id: 6444602274
# mas "MQTT Explorer", id: 1455214828
# mas "OTP Auth", id: 1471867429
# mas "Tailscale", id: 1475387142
# mas "Telegram", id: 747648890
# mas "The Unarchiver", id: 425424353
# mas "Windows App", id: 1295203466
